### ISSUE TITLE
slow upload speeds

### ISSUE THREAD

**Issue by lindseymao** [galaxyproject/galaxy-upload#6]
My internet speed through my institution is quite high, but the speed for uploading these files seems quite slow (2.0mb/s). What can I do to make it faster?

**Comment by natefoo** [comment]
I am not sure why it would be so slow in your case. There could be multiple factors, including filesystems on both sides and every hop of the network in between.

I did a bit of testing and from my institution I'm getting around 10 MB/s with galaxy-upload. A straight network performance test between myself and usegalaxy.org got around 30-60 MB/s. This isn't too bad considering the additional overhead of the upload process (the protocol, shared service, and writing to a storage backend), but it could probably be better. I'll see if there's anything that can be done to improve this, but I am not sure if it would help in your case.
